import React, { useEffect, useRef, useState } from "react"
import { motion } from "framer-motion"
import { IconBrandLinkedin, IconBrandX, IconFileText } from "@tabler/icons-react"

export default function PromoCard() {
    const [open, setOpen] = useState(true)
    const tweetText = encodeURIComponent("Hey I'm Yacine and I'm a nice guy who applied to the SWE Mistral internship — my background is also nice and unexpected :)")
    const tweetIntentUrl = `https://twitter.com/intent/tweet?text=${tweetText}`
    const tweetId = "1967339867932954834" // set your tweet id here to enable direct Repost
    const repostUrl = tweetId ? `https://twitter.com/intent/retweet?tweet_id=${tweetId}` : tweetIntentUrl

    const videoRef = useRef<HTMLVideoElement | null>(null)

    useEffect(() => {
        const video = videoRef.current
        if (!video) return

        const setRate = () => {
            try {
                video.playbackRate = 2
            } catch { }
            // Ensure autoplay works across browsers
            video.muted = true
            try {
                video.play().catch(() => { })
            } catch { }
        }

        if (video.readyState >= 1) {
            setRate()
        } else {
            video.addEventListener("loadedmetadata", setRate)
        }

        return () => {
            video.removeEventListener("loadedmetadata", setRate)
        }
    }, [])

    const handleVideoClick = () => {
        const video = videoRef.current
        if (!video) return
        if (video.paused) {
            video.play().catch(() => { })
        } else {
            video.pause()
        }
    }

    if (!open) return null

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setOpen(false)} />

            <motion.div
                initial={{ opacity: 0, scale: 0.96, y: 8 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                transition={{ duration: 0.35, ease: [0.25, 0.46, 0.45, 0.94] }}
                className="relative mx-4 w-full max-w-3xl overflow-hidden rounded-2xl border border-white/10 bg-black/75 backdrop-blur-md text-white"
            >
                {/* close button */}
                <button
                    onClick={() => setOpen(false)}
                    aria-label="Close"
                    className="absolute right-3 top-3 text-3xl z-10 h-8 w-8 rounded-full text-white/70 hover:text-white"
                >
                    ×
                </button>

                <div className="relative p-8 sm:p-10">
                    <div className="flex flex-col items-center text-center">
                        <p className="text-2xl sm:text-3xl font-semibold text-white/90">Hey I'm Yacine 👋</p>
                        {/* disclaimer */}
                        <div className="mt-2 w-full max-w-2xl rounded-lg bg-white/5 px-4 py-3 text-sm sm:text-base text-white/90">
                            <span className="font-semibold">Disclaimer:</span> this project is <span className="bold">not commercial</span>. It's only for my <span className="bold">internship application</span> and a suggestion for refreshed <span className="bold">branding</span> and new features — like rendering <span className="bold">charts directly inside the chat</span> (no more static images generated by matplotlib).
                        </div>

                        <div className="mt-5 w-full max-w-2xl">
                            <div className="relative">
                                <video
                                    ref={videoRef}
                                    src="/demo.webm"
                                    autoPlay
                                    muted
                                    loop
                                    playsInline
                                    onClick={handleVideoClick}
                                    className="w-full rounded-xl object-cover shadow-xl cursor-pointer"
                                />
                            </div>
                        </div>
                        <p className="mt-3 text-xs sm:text-sm text-white/80">This is my home task for Mistral.</p>
                        <div className="mt-5 w-full max-w-2xl grid grid-cols-1 sm:grid-cols-3 gap-3">
                            <a
                                href="/resume.pdf"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex w-full justify-center items-center rounded-lg border border-white/20 hover:border-white/40 px-4 py-2.5 text-sm font-medium transition-colors"
                            >
                                <IconFileText size={18} className="mr-2" />
                                My CV
                            </a>
                            <a
                                href={repostUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex w-full justify-center items-center rounded-lg border border-white/20 hover:border-white/40 px-4 py-2.5 text-sm font-medium transition-colors"
                            >
                                <IconBrandX size={18} className="mr-2" />
                                Repost
                            </a>
                            <a
                                href="https://www.linkedin.com/in/yacine-alloul-96295a229/"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex w-full justify-center items-center rounded-lg border border-white/20 hover:border-white/40 px-4 py-2.5 text-sm font-medium transition-colors"
                            >
                                <IconBrandLinkedin size={18} className="mr-2" />
                                LinkedIn
                            </a>
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>
    )
}
