import React, { useState } from "react"
import { motion } from "framer-motion"
import { IconBrandX } from "@tabler/icons-react"

export default function PromoCard() {
    const [open, setOpen] = useState(true)
    const tweetText = encodeURIComponent("Hey I'm Yacine and I'm a nice guy who applied to the SWE Mistral internship — my background is also nice and unexpected :)")
    const tweetIntentUrl = `https://twitter.com/intent/tweet?text=${tweetText}`
    const tweetId = "1967339867932954834" // set your tweet id here to enable direct Repost
    const repostUrl = tweetId ? `https://twitter.com/intent/retweet?tweet_id=${tweetId}` : tweetIntentUrl

    if (!open) return null

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setOpen(false)} />

            <motion.div
                initial={{ opacity: 0, scale: 0.96, y: 8 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                transition={{ duration: 0.35, ease: [0.25, 0.46, 0.45, 0.94] }}
                className="relative mx-4 w-full max-w-2xl overflow-hidden rounded-2xl border border-white/10 bg-black/75 backdrop-blur-md text-white"
            >
                {/* close button */}
                <button
                    onClick={() => setOpen(false)}
                    aria-label="Close"
                    className="absolute right-3 top-3 text-3xl z-10 h-8 w-8 rounded-full text-white/70 hover:text-white"
                >
                    ×
                </button>

                <div className="relative p-6 sm:p-8">
                    <div className="flex flex-col items-center text-center">
                        <div className="group relative">
                            <img
                                src="/chat-cat.png"
                                alt="Yacine's cat"
                                className="h-40 w-40 sm:h-48 sm:w-48 rounded-2xl object-cover border border-white/15 ring-1 ring-white/5 shadow-xl transition-transform duration-300 group-hover:scale-[1.02]"
                            />
                        </div>

                        <h3 className="mt-5 text-xl sm:text-2xl font-semibold tracking-tight">Le Chat says hi 👋</h3>
                        <p className="mt-3 text-base sm:text-lg text-white/90 max-w-xl leading-relaxed">
                            Hey I'm <strong>Yacine</strong> and I'm a nice guy who applied to the <strong>SWE Mistral</strong> — my background is also nice and unexpected :)
                        </p>

                        {/* disclaimer */}
                        <div className="mt-4 w-full max-w-xl rounded-lg bg-white/5 px-4 py-3 text-sm sm:text-base text-white/90">
                            <span className="font-semibold">Disclaimer:</span> this project is <strong>not commercial</strong>. It's only for my <strong>internship application</strong> and a suggestion for refreshed <strong>branding</strong> and new features — like rendering <strong>charts directly inside the chat</strong> (no more static images generated by matplotlib).
                        </div>


                        <div className="mt-4 flex flex-wrap items-center justify-center gap-3">
                            <a
                                href="/resume.pdf"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex items-center rounded-lg bg-white text-black hover:bg-white/90 px-4 py-2.5 text-sm font-medium transition-colors"
                            >
                                My CV
                            </a>
                            <a
                                href={repostUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex items-center rounded-lg border border-white/20 hover:border-white/40 px-4 py-2.5 text-sm font-medium transition-colors"
                            >
                                <IconBrandX size={18} className="mr-2" />
                                Repost
                            </a>
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>
    )
}
